<?php

$product_descriptions = [
    'oppo_mobile'=>'Display Super Retina XDR da 6,1" con ProMotion per un’esperienza ancora più fluida e reattiva Modalità Cinema con profondità di campo smart e spostamento automatico della messa a fuoco nei video. Nuovo sistema di fotocamere Pro da 12MP (teleobiettivo, grandangolo e ultra-grandangolo) con scanner LiDAR, zoom ottico 6x (estensione totale), fotografia macro, Stili fotografici, video ProRes, Smart HDR 4, modalità Notte, Apple ProRAW, registrazione video HDR a 4K con Dolby Vision. Fotocamera anteriore TrueDepth da 12MP con modalità Notte e registrazione video HDR a 4K con Dolby Vision. Chip A15 Bionic per prestazioni fulminee. Fino a 22 ore di riproduzione video. Robusto design con Ceramic Shield. Resistenza all’acqua di grado IP68, la migliore del settore. 5G per download velocissimi e streaming ad alta qualità. iOS 15 e le sue nuove funzioni per fare ancora di più con iPhone. Compatibilità con gli accessori MagSafe: aggancio rapido e ricarica wireless più veloce.',

    'panasonic_tv'=>'A smart tv with much more feature',

    'sony_tv'=>'A tv with much more feature',

    'longboard'=>'Un longboard molto bello.',

    'cinelli_king_zydeco'=>'Questo telaio unico permette performance estreme sulle superfici più diverse come asfalto, strade bianche e terreni impervi, grazie alla possibilità di montare ruote da 700c e 650b con copertoni fino a 2,1”. La costruzione in carbonio monoscocca e la sua geometria da corsa rendono questo telaio leggero e veloce. Perfettamente a suo agio sia in gare gravel su lunghe distanze che in esplorazioni con bike packing.',

    'trenta_e_lode'=>'Il voto che si merita questo bellissimo progetto.',

    'omega_x_swatch_sun'=>'Questa stella del firmamento di colore giallo acceso come il sole, presenta un raffinato quadrante spazzolato e un cinturino in VELCRO© bianco. La lancetta dei secondi del cronografo, le lancette dei quadranti secondari e la scala tachimetrica sono di colore arancione. Lo sfondo dei quadranti secondari e della lunetta sono invece bianchi. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_moon'=>'Fai (quasi) sul serio con questo orologio grigio acciaio, dotato di un cinturino in VELCRO© nero. Tutte le lancette e la scala tachimetrica sono di colore bianco, proprio come quelle del Moonwatch originale. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_mercury'=>'Con il suo colore grigio profondo intenso e il cinturino grigio metallico VELCRO©, questo orologio è sinonimo di affari. La lancetta dei secondi del cronografo, le lancette dei quadranti secondari e la scala tachimetrica sono di colore bianco. Lo sfondo dei quadranti secondari e della lunetta sono invece neri. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_venus'=>'Su questo orologio audace, il cinturino in VELCRO© bianco controbilancia in modo perfetto il rosa pastello polvere. I quadranti secondari ovali, impreziositi da dettagli in stile diamante sui bordi, conferiscono un tocco di femminile eleganza. La lancetta di ore, minuti e secondi del cronografo e le lancette dei quadranti secondari sono a loro volta rosa. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_earth'=>'Gli astronauti ecologisti ameranno questo orologio verde natura con cinturino in VELCRO© di colore blu marino. La lancetta dei secondi del cronografo e le lancette dei contatori sono di colore marrone. I quadranti secondari sono di colore bianco. Dello stesso colore è anche la scala tachimetrica sullo sfondo della lunetta blu. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_mars'=>'Per rendere onore a Marte, tonalità rosso ardente entrano in contrasto con il quadrante bianco brillante e il cinturino in VELCRO©. La lancetta dei secondi del cronografo è di colore rosso, mentre i quadranti secondari di ore e minuti presentano lancette uniche di colore rosso, con un\'allegra forma di navicella spaziale. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_jupiter'=>'Per quelli che amano mantenersi sul classico, questo orologio presenta eleganti tonalità beige che controbilanciano in modo perfetto il cinturino in VELCRO©. La lancetta dei secondi del cronografo e le lancette dei quadranti secondari sono di colore arancione. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_saturn'=>'Su questo modello, tonalità color sabbia e beige entrano dolcemente in contrasto con il quadrante marrone e il cinturino in VELCRO©. La lancetta dei secondi del cronografo, le lancette dei quadranti secondari e lo sfondo della scala tachimetrica sono a loro volta di colore marrone. Il quadrante secondario dei secondi rappresenta gli anelli di Saturno. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_uranus'=>'L\'etereo blu pastello incontra un cinturino in VELCRO© di colore bianco acceso su questo esemplare della collezione Mission. La lancetta del cronografo, le lancette dei contatori e lo sfondo della scala tachimetrica sono di colore bianco. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_neptune'=>'Un\'intensa combinazione di tonalità blu marino profondo e il cinturino in VELCRO© nero rendono questo orologio perfetto per gli amanti dei colori scuri. Per creare contrasto, la lancetta dei secondi del cronografo, le lancette dei quadranti secondari e la scala tachimetrica sono di colore bianco. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'omega_x_swatch_pluto'=>'Su questo orologio, tonalità di grigio chiaro alla moda entrano in contrasto con il cinturino in VELCRO© di colore grigio scuro. La lancetta dei secondi del cronografo e le lancette dei quadranti secondari sono di colore nero, mentre lo sfondo dei quadranti e della lunetta presentano due tonalità di bordeaux. Tutti i quadranti sono contraddistinti dal marchio OMEGA X SWATCH, nonché dall\'iconico logo Speedmaster e dal nuovo logo MoonSwatch. La struttura del vetro, la "S nascosta" integrata al centro, il motivo circolare raffinato ed elegante sull\'anello esterno del quadrante e i quadranti secondari, la struttura sottile e armoniosa degli aggetti, l\'iconico dettaglio del "punto sopra al 90" sulla lunetta con scala tachimetrica e, naturalmente, il tocco unico di Bioceramic sono caratteristiche comuni di tutti i modelli e dimostrano lo straordinario amore per i dettagli. Tutte le lancette di ore, minuti e secondi del cronografo e gli indicatori dell\'ora presentano il trattamento Superluminova, per una perfetta fosforescenza al buio.',

    'kensington_docking_station'=>'La docking station Thunderbolt 4 è compatibile universalmente, offre un\'uscita video in 4k Dual o in 8k Single ed è perfetta per ottimizzare lo spazio di lavoro in casa o in ufficio. Collega fino a 3 dispositivi Thunderbolt aggiuntivi con la tecnologia Thunderbolt 4 e fornisce velocità di trasferimento fino a 40 Gbps grazie al cavo Thunderbolt 4 da 0,8 m incluso. Carica i dispositivi in modo rapido e facile grazie ad un\'erogazione della potenza da 90 W ed un supporto completo per accessori periferici USB-C PD 3.0 o USB4. Include : 4 porte Thunderbolt 4, 4 porte USB-A (1 porta 5V / 1,5 A e 3 porte Gen2 a 10 Gbps), 1 porta Gigabit Ethernet, 1 jack audio combinato e 1 x UHS-II SD Lettore di schede 4.0. Contenuto: 1 x SD5700T Thunderbolt 4 Docking Station Dual in 4k, alimentatore, cavo Thunderbolt 4 da 0,8 m. Dimensioni: (L x A x P) 195 mm x 75 mm x 30 mm, Peso 435 g, grigio, K35175EU',

    'caldigit_cavo_thunderbolt_4'=>'Prestazioni estreme - 40 Gb/s per Thunderbolt 4 / USB 4 con il massimo throughput. Ideale per gli utenti che necessitano di una connessione stabile a larghezza di banda elevata. Ricarica potente - Fino a 100 W di power delivery e ricarica del computer portatile a 5 A 20 V = 100 W. Massima compatibilità - Compatibile con Thunderbolt 4, Thunderbolt 3, USB 4, USB-C Gen 1/2, USB 2.0. Ideale per MacBook Pro 2016+, iMac 2017+, iMac Pro 2017+, MacBook Air 2020+, PC e portatili Windows Thunderbolt 3/4, docking station Thunderbolt, dispositivi e periferiche di archiviazione ad alta velocità.',

    'borsone_north_face'=>'Tasca laterale con cerniera di sicurezza per telefono o portafoglio. Spallacci in stile alpino, rimovibili e regolabili. Apertura a D con cerniera e patta resistente alle intemperie. Scomparto principale con tasca in rete con cerniera di sicurezza. Materiale Base Camp resistente all\'acqua con travetta aggiuntiva e rinforzi a cucitura doppia.',

    'tappetino_da_taglio'=>'Tappeto da taglio grande a doppia faccia, con superficie antiriflesso e antiscivolo. Il materiale rigenerante si ripara da solo in caso di tagli superficiali. Massimizza la durata delle lame del tuo taglierino e protegge il piano di lavoro. Spessore da 3mm a triplo strato, è progettato per offrire una superficie flessibile ma resistente. Garanzia soddisfatti o rimborsati: se non dovessi essere completamente soddisfatto del prodotto, ti preghiamo di contattarci per ricevere una sostituzione gratuita o un rimborso completo.',

    'lampada_led_scrivania'=>'Cura degli occhi, regolazione continua della temperatura del colore regolabile: la testa della lampada da 40 cm offre un\'efficienza luminosa uniforme che copre tutta la scrivania, senza sfarfallio e abbagliamento. Regolazione continua della temperatura di colore regolabile (da 3000 K a 5500 K) con funzione memoria, ideale per ogni occasione: lettura, lavoro, giochi, disegni, hobby, fai da te, ecc. Lampada da scrivania flessibile con braccio oscillante. Design a tre assi e angolo regolabile liberamente. Testa della luce girevole, con cui è possibile regolare la direzione della luce secondo le proprie esigenze. Clip in metallo extra large, a risparmio energetico. Clip in metallo extra large, supporto forte per tavolo fino a 5,3 cm. La luce può essere facilmente fissata alla scrivania o al tavolo da ufficio, risparmiando spazio sulla scrivania. 98 LED ad alta efficienza consumano l\'80% in meno di energia rispetto alle tradizionali lampadine a incandescenza e hanno una durata di vita di 50.000 ore. Ciò significa una bolletta elettrica molto più bassa. e meno emissioni di CO2. Funzione timing, modalità lettura: imposta la funzione timer quando si desidera dormire. La luce si spegne automaticamente dopo il tempo impostato. (10 minuti o 40 minuti di ritardo). Accesso con un clic nella modalità di lettura (4000 K e 100% di luminosità), per godere di una piacevole lettura rilassata. Contenuto della confezione: 1 x lampada da scrivania (materiale: lega di alluminio di qualità aeronautica con finitura spazzolata), 1 x adattatore CE (lunghezza cavo di alimentazione 1,8 metri), 1 x manuale utente (lingua italiana non garantita). Servizio clienti sempre amichevole.',

    'tastiera_pieghevole_wireless'=>'Compatibilità: Compatibile con 3 sistemi operativi maggiori: iOS / Windows/ Android. Supporta la maggior parte dei dispositivi con bluetooth. Nota: questa tastiera è in Layout americano. Ultra sottile e leggera: Misura piegata: 16 * 10 * 1 cm, misura spiegata: 32 * 9.6 * 0.5 cm. Pesa solo 138.8g. Design magnetivo e innovativo per mettersi in borsa, portafoglio o tasca. Semplice acceso/spento: La tastiera è automaticamente accesa quando si apre ed è spento quando si chiude. Ricaricabile: Alimentato da batteria ricarica integrata, supporta un funzionamento continuo fino a 40 ore / standby di 30 giorni. Può essere ricaricato da cavo USB, che è incluso nel pacchetto. Design Ergonomico: Il keyset a dimensione normale ti offre un sensazione eccellente di touch e un\'esperienza comoda di digitazione.',

    'max_cases_trolley_620_460_340'=>'Utilizzo: pratico trolley con ruote ideale per trasportare e proteggere apparecchiature e materiali sensibili. Caratteristiche: valigia ermetica trolley vuoto resistente all\'acqua, alle polveri, agli urti ed agli agenti atmosferici, chiusura di sicurezza a doppio step, manico morbido ad alta ergonomicità. Dettagli: valvola automatica di pressurizzazione, punti di fissaggio, pareti spesse antiurto, valigia 100% riciclabile, retro maniglia telescopica a scomparsa e ruote con assale in acciaio inox. Certificazioni: IP67 (100% impermeabile), STANAG 4280, DEF STAN 81-41, NATO (NSN), ATA300, 100% made in Italy. Dimensioni (lunghezza x larghezza x altezza in millimetri): esterne 687 x 528 x 366 , interne 620 x 460 x 340 , profondità coperchio 60 , profondità fondo 280.',

    'max_cases_trolley_538_405_245'=>'Utilizzo: pratico trolley con ruote ideale per trasportare e proteggere apparecchiature e materiali sensibili. Caratteristiche: valigia ermetica trolley vuoto resistente all\'acqua, alle polveri, agli urti ed agli agenti atmosferici, chiusura di sicurezza a doppio step, manico morbido ad alta ergonomicità. Dettagli: valvola automatica di pressurizzazione, punti di fissaggio, pareti spesse antiurto, valigia 100% riciclabile, retro maniglia telescopica a scomparsa e ruote con assale in acciaio inox. Certificazioni: IP67 (100% impermeabile), STANAG 4280, DEF STAN 81-41, NATO (NSN), ATA300, 100% made in Italy. Dimensioni (lunghezza x larghezza x altezza in millimetri): esterne 594 x 473 x 270, interne 538 x 405 x 245, profondità coperchio 50, profondità fondo 195.',

    'cucchiaini_lunghi_inox'=>'Prodotto di ottima qualità: questi cucchiai per mescolare sono realizzati in acciaio inox di qualità. Molto resistenti e durevoli, utilizzabili per mescolare tè freddo, caffè e cocktail. Stile di vita: design lussuoso ed elegante con sensibilità ergonomica, superficie rifinita con uno specchio di qualità superiore, bordo liscio senza punti di rottura. Goditi i tuoi momenti di svago in questa estate! Cucchiai con manico lungo: la lunghezza dei cucchiai è di 170 mm, perfetta per la maggior parte dei bicchieri, brocche e tazze. Indispensabili al bar, a casa e alle feste. Stile vitale: cucchiaio per gelato e latte macchiato, robusto e antiruggine, con buon manico per bambini, adulti. Acquistatelo sarete soddisfatti della vostra scelta. Godetevi il vostro tempo libero in questa estate. Lavabile in lavastoviglie: facile da pulire in lavastoviglie. Non distorti. In alternativa, è possibile lavarli facilmente con sapone e acqua calda e tenerli asciutti dopo il lavaggio.',

    'sony_SEL_24105G'=>'Ampio zoom da 24 a 105 mm con F4 costante. Gestisce facilmente soggetti quali ritratti, istantanee, paesaggi, architettura e molto altro ancora. Quattro elementi asferici, due dei quali ad alta precisione AA (advanced aspherical) che vengono utilizzati nel design ottico avanzato per eliminare efficacemente la distorsione. I tre elementi in vetro ED (dispersione estremamente bassa) vengono strategicamente inseriti nel percorso ottico dell\'obiettivo per aumentare la risoluzione. La massima apertura F4, luminosa e costante per tutte le ampiezze di zoom, mantiene la luminosità anche quando viene modificata la lunghezza focale. Con coperchio, modello: ALC-SH152.Tappo copriobiettivo anteriore: ALC-F77S.Tappo copriobiettivo posteriore: ALC-R1EM.Dotato di custodia.',

    'fenix_pd36r'=>'Corpo: alluminio aeronautico anodizzato con finitura anti-abrasiva.\nLente: vetro temperato ultra trasparente con trattamento antiriflesso.\nOutput: 30 - 150 - 350 - 800 - 1600 lumen - strobo.\nIntensità massima: 19977 cd.\nVisibilità massima: 283 m.\nAutonomia: 115 h a 30 lumen; 2 h e 50 min a 1600 lumen.\nAlimentazione: 21700 ricaricabile',

    'lexar_uhs_128gb'=>'Classe 10 con tecnologia UHS-I e classe di velocità 3, V30.\nVelocità di lettura fino a 633x, 95 MB/s.\nVelocità di scrittura 45 MB/s.\nInclude il software scaricabile Image Rescue.\nCompatibile con videocamere HD e fotocamere DSLR/3D.',

    'caramelle_bonelle'=>"Morbide caramelle gelées di sola pectina di frutta.\nAi gusti di Frutti di Bosco: Mora, Uva spina, Mirtillo, Lampone.\nSenza Coloranti artificiali e aromi artificiali.\nSenza Glutine.\n100% Vegan.",

    'tombow_airpress_black'=>"Tombow Airpress 0.7mm Ball Point Pen, Full Black by Tombow.\n1 Pack.",

    'tombow_airpress_green'=>"Penna a sfera con esclusiva tecnologia ad aria compressa.\nSempre e ovunque: scrive anche se usata con la punta verso l’alto, su carta bagnata, in ambienti polverosi e a temperature gelide (fino a -5 °C). L’accessorio ideale per sport all'aria aperta, viaggi, artigianato, scuola ecc.\nImpugnatura gommata: tenuta sicura anche in caso di pioggia, con dita o guanti umidi.\nColore della mina: nero, diametro della sfera: 0,7 mm. Mina: br-sf33.\nColore: verde lime.",

    'tombow_airpress_yellow'=>"Penna a sfera con esclusiva tecnologia ad aria compressa.\nSempre e ovunque: scrive anche se usata con la punta verso l’alto, su carta bagnata, in ambienti polverosi e a temperature gelide (fino a -5 °C). L’accessorio ideale per sport all'aria aperta, viaggi, artigianato, scuola ecc.\nImpugnatura gommata: tenuta sicura anche in caso di pioggia, con dita o guanti umidi.\nColore della mina: nero, diametro della sfera: 0,7 mm. Mina: br-sf33.\nColore: giallo.",

    'sony_wf_1000xm4'=>"ELIMINAZIONE DEL RUMORE: Il noise cancelling è potenziato grazie al novo processore V1, il driver, i microfoni di nuova generazione e gli innovativi auricolari in poliuretano.\nAUDIO HI-RES WIRELESS: Con un driver da 6 mm, il diaframma ad alta flessibilità ed il processore V1, riproducono un suono dinamico senza distorsioni e una ricca gamma di bassi nonostante le loro dimensioni ridotte.\nSPEAK TO CHAT: Non appena parli con qualcuno, la funzione Speak-to-Chat mette automaticamente in pausa la musica. Molto utile, se vuoi tenere gli auricolari indossati e le tue mani sono occupate!\nCHIAMATE A MANI LIBERE: La tecnologia Precise Voice Pickup consente agli auricolari di captare la tua voce in modo chiaro e preciso.\nBATTERIA A LUNGA DURATA: Con una sola ricarica avrai 8 ore di autonomia e altre 16 ore di ricarica sfruttando la custodia. Inoltre 5 minuti carica basteranno per 60 minuti di riproduzione.",

    'sony_wh_1000xm4'=>"Cancellazione del rumore leader del settore, alimentata dal nostro processore noise cancelling HD QN1 con algoritmo evoluto e dal nuovo Chip Bluetooth.\nQualità audio premium: supportano Hi-Res Audio e ottimizzano i file musicali compressi tramite la nuova tecnologia DSEE Extreme.\nSPEAK-TO-CHAT mette automaticamente in pausa la musica quando si avvia una conversazione per un'esperienza di ascolto senza mani e senza interruzioni.\nWEARING DETECTION: questa funzione smart spegne le cuffie quando non le si indossa.\nCon la Multi-Point Connection, le cuffie Sony possono essere associate contemporaneamente a due dispositivi Bluetooth.",

    'bose_700'=>"Potenti cuffie con riduzione del rumore: 11 livelli di riduzione del rumore attiva ti consentono di goderti musica, podcast, video e chiamate senza distrazioni.\nSuono sorprendente: dettagli nitidi e chiari. Bassi ricchi e profondi. Queste cuffie wireless offrono un suono realistico e coinvolgente, pieno e bilanciato a qualsiasi volume.\nAcquisizione vocale impareggiabile: un sistema di microfoni rivoluzionario si adatta agli ambienti rumorosi e ventosi, garantendo una qualità audio cristallina durante le chiamate.\nTesta alta e mani libere: grazie alla facilità di accesso agli assistenti vocali come Alexa e Assistente Google per musica, navigazione, meteo e altro ancora, e ai comandi touch intuitivi sui padiglioni, puoi rimanere connesso senza bisogno di usare il telefono.\nDesign e comfort straordinari: grazie all'archetto leggero in acciaio inox e ai padiglioni inclinati per un comfort ottimale, puoi indossare comodamente queste cuffie Bluetooth per ore.\nFino a 20 ore di musica non-stop: la batteria wireless ti garantisce fino a 20 ore di autonomia con una sola ricarica.\nUn solo tocco per ascoltare Spotify: ascolta istantaneamente la tua ultima sessione su Spotify o scopri nuova musica tenendo premuto il dito sul padiglione destro. Al momento disponibile solo utilizzando le cuffie con dispositivi iOS.",

    'sennheiser_hd_660_s'=>"Cuffia dinamica aperta reference-class.\nDesign migliorato, per una distorsione armonica davvero bassa.\nDriver delle cuffie a selezione manuale con tolleranze esatte di accoppiamento sinistra e destra (± 1 dB) per la ottima precisione.\nImpedenza nominale 150 Ohm per consentire una connessione diretta con lettori HiRes fissi ma anche mobile.\nCavo scollegabile rinforzato in fibra para-aramidica con cavo in rame di ottima conduttività OFC, per un basso rumore di fondo.",

    'bose_qc45'=>"Cuffie con riduzione del rumore: l'equilibrio perfetto di silenzio, comfort e suono. Bose utilizza minuscoli microfoni per misurare, confrontare e contrastare i rumori esterni e ridurli attraverso il segnale opposto.\nAlta fedeltà: l'architettura acustica TriPort offre un suono profondo e pieno. Active EQ con ottimizzazione in base al volume offre sempre prestazioni audio bilanciate, con bassi uniformi a volume ridotto e musica sempre nitida ad alto volume.\nModalità Quiet e Aware: scegli la modalità Quiet per la riduzione completa del rumore o la modalità Aware per ascoltare il mondo esterno con le tue cuffie around-ear e goderti la musica rimanendo consapevole dell'ambiente circostante.\nCuffie over-ear: queste cuffie wireless sono talmente comode da poter essere indossate tutto il giorno. Realizzate in morbida pelle sintetica e nylon resistente agli urti, esercitano una pressione minima e sono lussuose e durevoli.\nFino a 24 ore di autonomia: la batteria garantisce fino a 24 ore di utilizzo con una sola carica.* Una ricarica rapida di 15 minuti offre 3 ore di riproduzione quando sei in giro oppure collega il cavo audio incluso per un'autonomia maggiore.\nCuffie around-ear con ricarica tramite USB-C: le cuffie si caricano tramite il cavo USB-C in dotazione.\nCuffie Bluetooth wireless con riduzione del rumore: queste cuffie sono ottimizzate per offrire una connessione Bluetooth forte e affidabile entro 9 m di distanza dal dispositivo associato.",

    'sennheiser_momentum_3'=>"Riproduzione più rapida della musica con la funzione auto on / off e smart pause che rilevano quando le cuffie sono riposte nella custodia o non utilizzate.\nScegli il tuo suono in base all'ambiente circostante: la funzione avanzata di active noise cancelling offre tre modalità di ascolto personalizzate per ambienti diversi e la funzione tranrent hearing ti consente di conversare senza rimuovere le cuffie.\nGoditi un comfort e un design superiori grazie all'archetto robusto in acciaio opaco ed a poggiatesta e padiglioni in vera pelle.\nInterazione semplice: controllo intuitivo per la musica ed accesso rapido agli assistenti vocali quali Alexa, Apple, Siri e Google sui dispositivi smart.\nResta sempre connesso con l'app sennheiser smart control per la personalizzazione e utilizza l'app tile per ritrovare e individuare le cuffie quando sono fuori posto.",

    'rode_nt_usb'=>"Presa mini jack stereo per monitoring tramite cuffia stereo senza latenza.\nControllo del mix tra sorgente (dal computer, per esempio base musicale) e ripresa (per esempio la propria voce).\nCompatible con Apple iPad.\nPattern polare cardioide.\nRisposta in frequenza 20Hz~20kHz.\nCollegamento di uscita USB.\nPrincipio Acustico: gradiente di pressione.",

    'rode_podcaster_usb'=>"Broadcast Sound Qualità.\n28mm dynamic capsule.\n18-bit resolution, 8-48kHz sampling.",

    'shure_sm7b'=>"UN SOLO MICROFONO PER TUTTO: Registrazione in studio, home recording, podcasting e streaming; L'SM7B è il microfono su cui fanno affidamento cantanti, podcaster e streamer più affermati al mondo.\nREGISTRAZIONE DELLA VOCE IN STUDIO: La capsula dinamica dell'SM7B produce una risposta in frequenza ampia, omogenea e lineare, capace di offrire una riproduzione eccezionalmente chiara e naturale sia della musica che del parlato.\nPODCAST & BROADCAST: Presente nei più importanti podcasting-studios di tutto il mondo, l'SM7B dispone di un sistema antishock con sospensione pneumatica e di un filtro antipop che consentono di eliminare i rumori meccanici e i disturbi causati dal respiro; così vengono riprese solo le parole e tutto il resto rimane fuori dal mix.\nCONTENUTI IN STREAMING: Una diretta streaming professionale comincia da un microfono capace di riprendere con eccezionale naturalezza sia la musica sia il parlato; il microfono SM7B da decenni in ciò è un pioniere.\nCONNESSIONE XLR PROFESSIONALE: la connessione XLR congiuntamente a un'interfaccia audio permette un maggior controllo sul segnale e, quindi, una miglior qualità complessiva del suono; per ottenere il famoso tono caldo e bilanciato che contraddistingue l'SM7B, si consiglia un guadagno di almeno 60 dB.\nPATTERN POLARE A CARDIOIDE CLASSICO DALLA RIPRESA UNIFORME: il pattern polare a cardioide del microfono SM7B è concepito per assicurare la reiezione dei segnali fuori asse, permettendo così di cantare o parlare con un'angolazione confortevole, con la sicurezza che il suono verrà ripreso proprio come desiderato e con una colorazione ridotta la minimo.\nPROTEGGI IL TUO SUONO: abbiamo aggiunto una schermatura elettromagnetica evoluta per abbattere ogni ronzio generato dai monitor dei computer o da altre apparecchiature da studio.",

    'borraccia_24bottles'=>"LA BORRACCIA ORIGINALE DAL 2013: il design originale di Urban Bottle la rende la borraccia non termica più leggera e compatta per la tua idratazione quotidiana;\nMATERIALI DI ALTA QUALITÀ: Realizzata in Acciaio Inox 18/8 per uso alimentare, non rilascia nessuna sostanza nelle tue bevande, non si arrugginisce, non impartisce alcun sapore;\nDESIGN ORIGINALE ITALIANO: Tutti i prodotti 24Bottles sono disegnati in Italia con un'attenta ricerca e brevettati per garantire la miglior esperienza di utilizzo;\nTOTALMENTE LEAKPROOF: Tutti I prodotti 24Bottles sono a chiusura ermetica, permettendoti di portarli con te in tutta sicurezza, senza perdere una goccia;\nECO FRIENDLY AD EMISSIONI ZERO: Tutti i prodotti 24Bottles sono a emissioni zero grazie al sostegno di molteplici progetti di riforestazione in tutto il mondo;",

    'drop_alt_mechanical_keyboard'=>"The Drop ALT mechanical keyboard is just like the CTRL, but with 67 keys instead of 87. Absent of function keys, it wastes no space—but it still has a full set of arrows and numerals. Constructed with a solid aluminum frame with a built-in switch plate, the ALT is rock solid. And thanks to the hot-swap switch sockets, it allows you to swap switches whenever you want with no soldering required. It’s also fully programmable via QMK, meaning you can assign macros or custom keybinds to every key. With dual USB-C connectors, the ALT is outfitted with the latest connections. What’s more, it has customizable RGB backlighting and underlighting. Set it to a single color or light it up with a rainbow wave pattern. To enhance the backlighting, there are shine-through doubleshot PBT keycaps, too. Grab it with your choice of switches to get just the feel you want.",

    'drop_ctrl_mechanical_keyboard'=>"To put it simply, the CTRL mechanical keyboard has it all. Constructed with a solid aluminum frame with a built-in switch plate, it’s stable and fortified. And thanks to the hot-swap switch sockets, it allows you to change switches whenever you want with no soldering required. It’s also fully programmable via QMK, meaning you can assign macros or custom keybinds to every key. With dual USB-C connectors, the CTRL is outfitted with the fastest available connections. Aesthetically, the keyboard is equally impressive. Featuring customizable RGB backlighting and underlighting, it puts on a colorful show; or you can set it to a single color for a more subtle look. The shine-through PBT keycaps only enhance the performance. What’s more, the keyboard comes with your choice of switches, so you can get just the feel you like—whether you prefer something heavy and tactile or lightweight and linear.",

    'logitech_g502'=>"Design Premium: la forma iconica del mouse ottico da gaming per PC si è evoluta ulteriormente con l'arrivo del wireless, aumentando anche le prestazioni del gioco.\nLIGHTSPEED Wireless: la Frequenza di aggiornamento di livello professionale di 1 ms offre prestazioni e libertà di movimento, senza compromessi in termini di peso, durata della batteria o latenza.\nSensore HERO 25K: il sensore HERO offre prestazioni da gamer professionista, con un tracciamento di precisione fino a 25 600 DPI e prestazioni pixel con assenza di smoothing o lag.\n11 Pulsanti: I pulsanti principali sono dotati di sistema di tensionamento meccanico per comandi rapidi e precisi; Personalizza tasti di scelta rapida e macro per ogni gioco e app.\nBilanciamento e Colore Regolabili: personalizza il bilanciamento del tuo mouse gaming RGB con sei pesi regolabili per il tracciamento, il movimento e il targeting dei pixel ottimale.\nRequisiti: Windows 7 o versioni successive, Mac OS X 10.11 o versioni successive, Chrome O, porta USB; accesso a Internet per il download del software Logitech G HUB.",

    'logitech_g902'=>"Sensore HERO 25K: il nostro sistema più avanzato con tracking 1:1, 400plus IPS e 25.600 DPI max; zero smoothing, filtraggio o accelerazione e 10x di efficienza energetica rispetto alla precedente gen.\nLIGHTSPEED Wireless: la Frequenza di aggiornamento di livello professionale di 1 ms offre prestazioni e libertà di movimento, senza compromessi in termini di peso, durata della batteria o latenza.\nDurata della batteria LiPo di 140 ore: grazie all'efficienza del sensore HERO 25K, la batteria di G903 dura fino a 140 ore con illuminazione RGB attiva e 180 ore senza illuminazione.\nCompatibile con sistema di ricarica wireless POWERPLAY: non dovrai preoccuparti mai della durata della batteria; aggiungi il sistema di ricarica wireless POWERPLAY per mantenere sempre carico il tuo G903 e gli altri mouse G compatibili, durante il gioco e quando non sono in uso; sistema di ricarica wireless POWERPLAY venduto separatamente.\nRGB LIGHTSYNC: l'illuminazione intelligente a spettro completo risponde all'azione del gioco: Con il software G HUB, l'audio e il colore dello schermo personalizzano gli effetti di luce da fino a 16.8 milioni di colori, che vengono sincronizzati in tutta la tua attrezzatura Logitech G.\nDesign ambidestro: il layout dei pulsanti configurabile consente di regolare l'uso con la mano destra o con la sinistra utilizzando il software Logitech G HUB per personalizzare i pulsanti programmabili (da 7 a 11).\nRequisiti: Windows 7 o versioni successive, macOS 10.11 o versioni successive, Chrome OS, porta USB, accesso a Internet per Logitech G HUB (opzionale).",

    'logitech_mx_master'=>"PENSATO PER MAC: Il mouse wireless MX Master 3 è progettato per il mondo Apple. Ottieni di più dal tuo Mac e iPad grazie alle funzionalità avanzate. Il design Space Gray combina design e performance.\nSCORRIMENTO SUPER RAPIDO: Con lo scroller elettromagnetico MagSpeed cambi modalità rapidamente e velocizzi il flusso di lavoro. La tecnologia svizzera assicura precisione, velocità e silenziosità.\nCONTROLLI INTUITIVI: Disegnato ergonomicamente per avvolgere la tua mano, MX Master 3 per Mac offre controlli strategicamente posizionati per i pollici. Crea, lavora e gioca in modo più intuitivo.\nMULTITASKING E VERSATILE: Muoviti fluidamente tra computer, iPad e laptop. Controlla diversi dispositivi allo stesso tempo grazie a Flow, per un flusso di lavoro ideale tra mouse e tastiera.\nFACILE DA CONTROLLARE: Muovi il mouse per passare facilmente tra desktop, Launchpad e Mission Control, tutto con il semplice tocco dei pulsanti con sistema \"gesture\".\nPERSONALIZZAZIONI PER APP: MX Master 3 è dotato di profili su misura per macOS e app specifiche, inclusi i settaggi programmabili per giocare, creare, lavorare e usare app per PC su Mac.\nREQUISITI DI SISTEMA: Bluetooth Low Energy, macOS 10.15 o successivo, iPadOS 13.4 o successivo.",

    'astuccio_eastpack'=>"Scomparto principale in cui riporre le tue penne e molto altro ancora.\nAltezza: 6 cm, Larghezza: 20.5 cm, Profondità: 7.5 cm.\nRealizzato in misto nylon 60% e poliestere 40%.\nNon è stato usato alcun tipo di prodotto animale per realizzare questo articolo vegano al 100%."
];
